name: chronologe
description: "Let your day write itself."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  envied: ^1.3.8
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  google_fonts: ^8.2.1
  image_picker: ^1.2.3
  local_auth: ^3.0.2
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  table_calendar: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  envied_generator: ^1.3.8

flutter:
  uses-material-design: true
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/fraunces_variable.ttf
