// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47WRhgKbb1NB4gf7hSSDDWr7IzFX30HA',
    appId: '1:615698325646:android:3a97b8f26dc6de5b1da9df',
    messagingSenderId: '615698325646',
    projectId: 'chronologe-test',
    storageBucket: 'chronologe-test.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_JCTCXK5cyCM3uWKzPqjj8taNDtVjvE',
    appId: '1:615698325646:ios:867bbd483a6730a51da9df',
    messagingSenderId: '615698325646',
    projectId: 'chronologe-test',
    storageBucket: 'chronologe-test.firebasestorage.app',
    androidClientId: '615698325646-h9k59plio4fcvsit4vpm9ca0edb2fk5m.apps.googleusercontent.com',
    iosClientId: '615698325646-eiufbt9ud15i2a0rboofv52f8lj319a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chronologe',
  );
}
